typography_spectrum: 0.53489
color:
  brandColors:
    - '#f0eeef'
    - '#b5b3b8'
    - '#6d6968'
    - '#959394'
    - '#60433f'
  brandStrength: 0.875
  lightness: 0.49535182071849704
  saturation: 0.7232125755399466
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Justin Bradshaw
  email: jstn.bradshaw@gmail.com
name: JustinBradshaw
cta:
  domain: null
  bucket: null
  version: null
navigation: []
favicon: null
title: Justin Bradshaw
description: paintings
purpose: []
