name: JustinBradshaw
favicon: null
layout_spectrum: 0.98226
typography_spectrum: 0.53489
title: Justin Bradshaw
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0eeef'
    - '#b5b3b8'
    - '#6d6968'
    - '#959394'
    - '#60433f'
  brandStrength: 0.875
  lightness: 0.49535182071849704
  saturation: 0.7232125755399466
  rhythmicContrast: 0.25
purpose: []
