typography_spectrum: 0.0037869096267968416
color:
  brandColors:
    - '#595241'
    - '#B8AE9C'
    - '#FFFFFF'
    - '#ACCFCC'
    - '#8A0917'
  brandStrength: 0.4987505155149847
  lightness: 0.4415376407559961
  saturation: 0.8928320046979934
  rhythmicContrast: 0.7069118400104344
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9813541872426867
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Justin Bradshaw
  email: jstn.bradshaw@gmail.com
name: JustinBradshaw
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Judith
    id: 5fcf0365-c5ea-4d9e-a0ea-2bc7eff5760f
    type: content
favicon: null
title: Justin Bradshaw
description: paintings
purpose: []
