typography_spectrum: 0.9688600553199649
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.7229095478542149
  lightness: 0.160587438615039
  saturation: 0.5193219089414924
  rhythmicContrast: 0.3409965333994478
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8527517267502844
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Justin Bradshaw
  email: jstn.bradshaw@gmail.com
name: JustinBradshaw
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Justin Bradshaw
description: paintings
purpose: []
